name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # if one fails, do not cancel the other
      matrix:
        gambit-version: ['', '--with-gambit=master']
        shared-mode: ['', '--enable-shared']
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get -y install openssl libssl-dev sqlite3 libsqlite3-dev
      - name: Configure Gerbil
        run: ./configure --prefix=/opt/gerbil ${{ matrix.gambit-version }} ${{ matrix.shared-mode }}
      - name: Create Gerbil version file
        run: echo "(define (gerbil-version-string) \"git-$(git rev-parse --short=8 HEAD)\")" > src/gerbil/boot/runtime/gx-version.scm
        run: echo "(define (gerbil-version-string) \"git-$(git rev-parse --short=8 HEAD)\")" > src/gerbil/runtime/version.ss
      - name: Prepare Build
        run: |
           . ./build-env.sh
           ./src/build.sh prepare
      - name: Build Gambit
        run: |
           . ./build-env.sh
           ./src/build.sh gambit
      - name: Build Gerbil boot gxi
        run: |
           . ./build-env.sh
           ./src/build.sh boot-gxi
      - name: Build Gerbil stage0
        run: |
          . ./build-env.sh
          ./src/build.sh stage0
      - name: Build Gerbil stage1
        run: |
          . ./build-env.sh
          ./src/build.sh stage1
      - name: Build Gerbil stdlib
        run: |
          . ./build-env.sh
          ./src/build.sh stdlib
      - name: Build Gerbil libgerbil
        run: |
          . ./build-env.sh
          ./src/build.sh libgerbil
      - name: Build Gerbil lang
        run: |
          . ./build-env.sh
          ./src/build.sh lang
      - name: Build Gerbil r7rs-large
        run: |
          . ./build-env.sh
          ./src/build.sh r7rs-large
      - name: Build Gerbil srfi shims
        run: |
          . ./build-env.sh
          ./src/build.sh srfi
      - name: Build Gerbil tools
        run: |
          . ./build-env.sh
          ./src/build.sh tools
      - name: Install Gerbil
        run: ./install.sh
      - name: Run Gerbil tests
        run: |
          export PATH=/opt/gerbil/bin:$PATH
          gxtest src/gerbil/test/...
          gxtest src/std/...
