name: MACOSCI
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-14
    strategy:
      fail-fast: false  # if one fails, do not cancel the other
      matrix:
        gambit-version: ['', '--with-gambit=master']
        shared-mode: ['', '--enable-shared']
        gcc-version: ['13', '14']
    steps:
      - uses: actions/checkout@v3
      - name: Configure and make Gerbil
        shell: bash
        run: |
          export CC=gcc-${{ matrix.gcc-version }}
          export GERBIL_GCC=gcc-${{ matrix.gcc-version }}
          export CXX=g++-${{ matrix.gcc-version }}
          export LDFLAGS='-Wl,-ld_classic'
          export GERBIL_BUILD_CORES=4
          ./configure --prefix=/opt/gerbil ${{ matrix.gambit-version }} ${{ matrix.shared-mode }}
          make -j$GERBIL_BUILD_CORES
      - name: Install Gerbil
        run: sudo make install
      - name: Run Gerbil tests
        run: |
          export PATH=/opt/gerbil/bin:$PATH
          gxtest -q src/gerbil/test/... src/std/... src/lang/... src/tools/...
