name: MACOSCI
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-14
    strategy:
      fail-fast: false  # if one fails, do not cancel the other
      matrix:
        gambit-version: ['', '--with-gambit=master']
        shared-mode: ['', '--enable-shared']
    steps:
      - uses: actions/checkout@v3
      - name: Configure Gerbil AND Make
        run: |
	     ./configure --prefix=/opt/gerbil ${{ matrix.gambit-version }} ${{ matrix.shared-mode }}
      - name: Install Gerbil
        run: ./install.sh
      - name: Run Gerbil tests
        run: |
          export PATH=/opt/gerbil/bin:$PATH
          gxtest -q src/gerbil/test/... src/std/... src/lang/... src/tools/...
